### ISSUE TITLE
Double Validation

### ISSUE THREAD

**Issue by firmai** [DenisVorotyntsev/CategoricalEncodingBenchmark#3]
Thanks for the work, just a quick question, what do you mean with the different type of validations?

**Comment by skeller88** [comment]
I think what @firmai is asking for is an explanation of each type of validation. [The blog post associated with this repo gives an explanation](https://towardsdatascience.com/benchmarking-categorical-encoders-9c322bd77ee8), or you can look at the classes in [utils.py](https://github.com/DenisVorotyntsev/CategoricalEncodingBenchmark/blob/f084847538ca949b0093e0d164672b5dcbe41854/utils.py) for the code details.

**Comment by skeller88** [comment]
However, it doesn't seem like the blog post explanation completely matches the code. From the code, here's what I see:

In None Validation, there is one training fold. In Single and Double Validation, there are multiple cv training folds. In Single Validation, there's one transform fold. In Double Validation, there are multiple transform folds.

For each training fold:
-> For each transform fold:
  -> fit a new encoder
-> Average the transformations across all transformation folds

Lastly, I think there's a bug on [this line](https://github.com/DenisVorotyntsev/CategoricalEncodingBenchmark/blob/f084847538ca949b0093e0d164672b5dcbe41854/utils.py#L123). It should be `val_t / self.n_folds / self.n_repeats` right?

**Comment by DenisVorotyntsev** [comment]
@skeller88 

> Lastly, I think there's a bug on this line. It should be val_t / self.n_folds / self.n_repeats right?

There is no bug here: we split data into several folds, fit encoder using training part, and encode validation part (treat it as OOF predictions); the splitting is repeated several times (`n_repeats`) to reduce noise. Thus, we need to divide only by `n_repeats`.
