### ISSUE TITLE
Question on Validation

### ISSUE THREAD

**Issue by agilebean** [DenisVorotyntsev/CategoricalEncodingBenchmark#5]
Very interesting benchmarking!

Could you please elaborate what the terms 
```
- no validation
- single validation
- double validation
```
mean?

Why did you not do cross-validation?

**Comment by mushtakovdn** [comment]
@agilebean these terms clearly explained on medium (see post https://towardsdatascience.com/benchmarking-categorical-encoders-9c322bd77ee8)
